# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe4bf48b37d14904edd068bd4ce51c7f9e28514fd82acde19dbe3717f14e71289fe5a05b55325a53ef197e6787e682a4627aefa4dd244261f7706da794cd9463

test:
  secret_key_base: 5c28df2b4c878ce7a94d82a52ce52ad06949eae3231929298e61878615579615c9a9f3d158c294c9ad8b8c994c32d249cf724b65eabf176d0d117b9f1fb2c204

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
