source 'https://rubygems.org'


gem 'rails', '4.2.7'
gem 'pg',                             '~> 0.18.4'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'active_model_serializers'
gem 'httparty',                       '~> 0.13.3'
gem 'resque',                         '~> 1.25.2',    require: 'resque/server'

gem 'elasticsearch-model', github: 'elastic/elasticsearch-rails', branch: '5.x'
gem 'elasticsearch-rails', github: 'elastic/elasticsearch-rails', branch: '5.x'

group :development, :test do
    gem 'byebug'
end

group :development do
    gem 'web-console', '~> 2.0'

    gem 'spring'
end
